### PR TITLE
Prefund the precompiles so they don't charge creation cost on first use

### PR DESCRIPTION
**Pull request by axic**
Balances should be 1 wei.

### CODE REVIEW

**Comment by chfast** [comment]
Have you tested it?

**Comment by axic** [comment]
No, we'll need to.

**Comment by axic** [comment]
@ewasm/testing can you please test this genesis? Would be nice to merge.

**Comment by jwasinger** [comment]
`provided configuration is not well formatted` is the only error message I get when I try to spin up a node with this genesis.

**Comment by axic** [comment]
Can you try `balance: "1"` ?

**Comment by axic** [comment]
I thought that was fixed - apparently never pushed by fix :)

**Comment by axic** [comment]
@jwasinger does this works now?

**Comment by jwasinger** [comment]
Looks good

**Pull request merged**
